# Setup
title: James Reiati Blog
tagline: from Unity to Godot
url: https://jamesreiati.github.io
paginate: 1
baseurl: ""
permalink: :title/

kramdown:
    footnote_backlink: "&#10548;"

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-target-blank

# Optimize Jekyll
exclude:
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Specify the author for blog posts
author:
  name: James Reiati

# Custom vars
version: 1.3.0
github:
  repo: https://github.com/jamesreiati/jamesreiati.github.io
